# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf753b86c5c29483c96e737f90feb3ad1c7e24b93b747bf03702c172ea34bf6e9226778912dbf9d841663ccd2a3c737376b2162e48c33af93949685d90350a45

test:
  secret_key_base: af7522355ddf2affedb52af392b1099f66ac4684d65a356d68534d72f7c4c518c369747d2befb192268e7367140c81bf85403e89bbc461a65d7c40cfcb2ffb19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
